# frozen_string_literal: true

require "spec_helper"

module ThreadUnsafe
  class CowFarm
    include CowCounter
  end

  # NOTE: this class was auto-generated by Claude AI within Cursor
  RSpec.describe CowCounter do
    describe CowFarm do
      let(:farm) { described_class.new }

      describe ".cows" do
        it "starts at 0 after reset" do
          expect(described_class.cows).to eq(0)
        end
      end

      describe ".increment" do
        before { farm.increment(by: 2) }

        it "sets the internal __count to 2" do
          expect(farm.__count).to eq(2)
        end

        it "increments the cows counters by 1" do
          expect(farm.class.cows).to eq(0)
        end
      end
    end
  end
end
